branches:
  only:
    - master
    - dev

matrix:
  include:
    - name: 'Server'
      env: PACKAGE_LOCATION=server

language: node_js
before_install:
  - cd $TRAVIS_BUILD_DIR/$PACKAGE_LOCATION
install:
  - npm ci
before_script:
  - npm run prettier:check
  - npm run eslint:check
  - npm run tsc:check
script:
  - npm test
